# Generated by Django 5.1 on 2024-08-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_area_curso_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
